apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-docker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-docker-app
  template:
    metadata:
      labels:
        app: flask-docker-app
    spec:
      containers:
      - name: flask-docker-app
        image: shubh0509/flask-docker-app
        ports:
        - containerPort: 5000
